### ISSUE TITLE
Unable to release swap partitons

### ISSUE THREAD

**Issue by itchka** [NigelCunningham/Tuxonice-Userui#8]
With TOI enabled in the kernel it is impossible to release swap partitions. Irrespective of their state all swap partitions are grabbed by TOI turning swap off ins a running instance makes no different. Nor does the manipulation of the values in /sys/power/tuxonice. Of particular note is the value of  of image_exists which appears to be locked at -1 changing this to 0 one would have thought would release the swap partition but it is not possible to change the value.
This problem is particularly annoying when running installation programs since any change to the partition table involving swap partitions requires a reboot so the partition can be removed or resized.
The iso here https://abf.rosalinux.ru/platforms/openmandriva2014.0/products/132/product_build_lists/11685
should serve to demonstrate the issue. First install making sure you have a swap partition then try to reinstall after a reboot and you will see the issue as you will not be able to delete the swap partition without rebooting.
Passing resume=/dev/null on the kernel commandline effectively disables TOI by "breaking" it. Then it is possible to delete swap partitions.
Queries to itchka at compuserve.com or at irc  #openmandriva-cooker at freenode.net

**Comment by NigelCunningham** [comment]
This bug should be filed against TuxOnIce, please (not the userui part).
